version: "3.8"
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TokyoJoe138!
    ports:
      - 1433:1433
    volumes:
      - sql_data:/var/opt/mssql/data

volumes:
  sql_data:

